### ISSUE TITLE
Eclipse 4.4.2 + Scala 2.11.6 + Scalacheck 2.11_1.12.2 - NoClassDefFoundError: scala/util/parsing/combinator/Parsers

### ISSUE THREAD

**Issue by valtih1978** [axel22/scalacheck-tutorial#1]
Here is mine test

``` scala
  import org.scalacheck.Prop.forAll
  val propConcatLists = forAll { (l1: List[Int], l2: List[Int]) =>
    l1.size + l2.size == (l1 ::: l2).size }   //> propConcatLists  : org.scalacheck.Prop = Prop
  propConcatLists.check                           //> java.lang.NoClassDefFoundError: scala/util/parsing/combinator/Parsers
                                                  //|   at java.lang.ClassLoader.defineClass1(Native Method)
                                                  //|   at java.lang.ClassLoader.defineClass(Unknown Source)
```

and its results in Eclipse worksheet.

**Comment by valtih1978** [comment]
I had to download parsers.jar as http://stackoverflow.com/a/26157873/4550451 prescribes.
